export const SOCKET_ACTIONS = {
    SEND_LOCAL__JOIN_ROOM: "SEND_LOCAL__JOIN_ROOM",
    SEND_LOCAL__LEAVE_ROOM: "SEND_LOCAL__LEAVE_ROOM",
    SEND_LOCAL__JOINED: "SEND_LOCAL__JOINED",
    SEND_LOCAL__ICE_CANDIDATE: "SEND_LOCAL__ICE_CANDIDATE",

    GET_REMOTES__JOIN: "GET_REMOTES__JOIN",
    GET_REMOTES__JOINED: "GET_REMOTES__JOINED",
    GET_REMOTES__USER_LEFT: "GET_REMOTES__USER_LEFT",
    GET_REMOTES__ICE_CANDIDATE: "GET_REMOTES__ICE_CANDIDATE",
}